# This file is GENERATED by .github/workflows/release.yml.
# Do not edit by hand; edits will be overwritten on the next release.
# Source template: release/Formula/aidc.rb.tmpl
#
# This file is RUBY that runs unprivileged on every user's machine via
# `brew install`. See task-14's template threat model: any execution
# construct beyond the documented allowlist is rejected by `make lint`
# (release/lint-formula-template.sh).
class Aidc < Formula
  desc "AI Dev Container: sandboxed Claude Code, locked-down egress, taint detection"
  homepage "https://github.com/pacepace/aidc"
  url "https://github.com/pacepace/aidc/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "02fc4c12d1420d40c3daf8189dc17bf3c58c784457f4d4feb564d166a4da926e"
  license "MIT"

  depends_on "jq"
  depends_on "gettext" # provides envsubst

  def install
    # Install everything from the tarball EXCEPT tests/ (host smoke harness only;
    # not needed at runtime and would bloat the install). .devcontainer/ is
    # load-bearing (dev-base build context) but Dir["*"] omits dotfiles.
    libexec.install Dir["*", ".devcontainer"].reject { |f| f == "tests" }
    bin.install_symlink libexec/"scripts/aidc"
  end

  def caveats
    <<~EOS
      aidc requires Docker with the `docker compose` v2 plugin (bundled with Docker
      Desktop; on Linux install `docker-compose-plugin` alongside the engine).
      Install Docker from https://www.docker.com/products/docker-desktop/ (macOS)
      or your distro's package manager (Linux), and ensure the daemon is running:

        docker info

      First `aidc create` builds the dev container images locally (~10-15 min on a
      fresh install). Subsequent creates reuse the built images and complete in ~30s.

      After a `brew upgrade aidc`, the next `aidc create` will rebuild container
      images against the new Dockerfile (~10-15 min). Already-running sessions keep
      their old image until you `aidc kill` them. Old aidc image tags remain on disk
      until you remove them with docker (typically a few GB per prior version);
      cleanup is opt-in so you can keep them for rollback.

      To pin to a specific major.minor line (e.g. for compliance review):

        brew install aidc@1.0
        brew link --overwrite --force aidc@1.0
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aidc help").lines.first
  end
end
