# This file is GENERATED by .github/workflows/release.yml.
# Do not edit by hand; edits will be overwritten on the next release.
# Source template: release/Formula/aidc@version.rb.tmpl
#
# This file is RUBY that runs unprivileged on every user's machine via
# `brew install`. See task-14's template threat model: any execution
# construct beyond the documented allowlist is rejected by `make lint`
# (release/lint-formula-template.sh).
class AidcAT16 < Formula
  desc "AI Dev Container 1.6 - pinned major.minor for stability/compliance"
  homepage "https://github.com/pacepace/aidc"
  url "https://github.com/pacepace/aidc/archive/refs/tags/v1.6.0.tar.gz"
  sha256 "63da7f5c9277bbf4af23624055d0d37065665f33e0ecc30c05c43a4f05166a6d"
  license "MIT"

  keg_only :versioned_formula

  depends_on "jq"
  depends_on "gettext"

  def install
    # .devcontainer/ is load-bearing (dev-base build context); Dir["*"] omits dotfiles.
    libexec.install Dir["*", ".devcontainer"].reject { |f| f == "tests" }
    # keg_only suppresses the default bin/ symlink; no bin.install_symlink here so
    # `brew link --force` won't collide with the unversioned aidc formula's
    # bin/aidc. Users opt in explicitly (see caveats).
  end

  def caveats
    <<~EOS
      aidc@1.6 is keg-only and won't be on your PATH by default.

      For a quick check on this pinned version without switching defaults:
        #{HOMEBREW_PREFIX}/opt/aidc@1.6/libexec/scripts/aidc <subcommand>

      To switch your default `aidc` binary to this pinned version:
        brew unlink aidc 2>/dev/null
        brew link --overwrite --force aidc@1.6

      To go back to the latest unversioned aidc:
        brew unlink aidc@1.6
        brew link aidc
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{libexec}/scripts/aidc help").lines.first
  end
end
